#!/bin/sh

B26=`uname -r|cut -d'.' -f2`
if [ "$B26" -eq "4" ]; then
  module="chardev.o"
else
  module="chardev.ko"
fi

device="memdev"
group="root"
mode="664"

# invoke insmod with all arguments we got
/sbin/insmod -f $module || exit 1

major=`cat /proc/devices | awk "\\$2==\"$device\" {print \\$1}"`

echo "Major number = $major"

rm -f /dev/${device}*
mknod "/dev/${device}0" c $major 0
mknod "/dev/${device}1" c $major 1

chgrp $group /dev/${device}*
chmod $mode  /dev/${device}*


